%  Build script for "psfFit_Image.m". Tested using Visual Studio 2012 compiler

clear mx_psfFit_Image.mexw64 % so that we can overwrite the mexw64 file

% Note: compile with COMPFLAGS = "\D DEBUG ... " for debug output

% For static linking (no ceres.dll required, but big file, longer compilation time)
% mex LINKFLAGS="$LINKFLAGS /LIBPATH:..\ceres-windows\x64\Release libglog_static.lib ceres_static.lib " ...
%     COMPFLAGS="$COMPFLAGS /openmp ...
%     ... /D DEBUG ...
%     /D CERES_USING_STATIC_LIBRARY /D GOOGLE_GLOG_DLL_DECL= ...
%     /I ..\ceres-windows\ceres-solver\include /I ..\ceres-windows\win\include ...
%     /I ..\ceres-windows\glog\src /I ..\ceres-windows\glog\src\windows /I ..\ceres-windows\eigen" -v ...
%     mx_psfFit_Image.cpp

% For dynamic linking 
mex LINKFLAGS="$LINKFLAGS /LIBPATH:..\ceres-windows\x64\Release ceres.lib libglog_static.lib" ...
    COMPFLAGS="$COMPFLAGS /openmp ...
    ... /D DEBUG ...
    /D GOOGLE_GLOG_DLL_DECL= ...
    /I ..\ceres-windows\ceres-solver\include /I ..\ceres-windows\win\include ...
    /I ..\ceres-windows\glog\src /I ..\ceres-windows\glog\src\windows /I ..\ceres-windows\eigen" -v ...
    mx_psfFit_Image.cpp